chat: new notification system in place (but all existing notifications need to be converted)
previously:
notification -> pop-up
warning: print msg to console with WARNING label
error: print msg to console with ERROR label

now:
warning: warning msg to console
warning -n: warning msg to console AND pop-up
error: error msg to console
error -n: error mst to console AND pop-up